# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project with Vite
        run: npm run build  # Comando de build do Vite
        working-directory: .  # Certifique-se de estar na raiz do repositório

      # Verifica se o diretório dist foi gerado corretamente
      - name: List build directory
        run: ls -la ./dist  # Lista o conteúdo do diretório dist para depuração

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./dist/*  # Certifique-se de que estamos pegando todos os arquivos dentro do dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
